name = "breeze"
description = "A light theme"
license = "MIT"
homepage = "https://github.com/Palpatineli/breeze-theme.git"
min_version = "0.4.0"

[extra]

[author]
name = "Keji Li"
homepage = "https://keji.li"
